sonar.organization=jhonabruzzi278
sonar.projectKey=jhonabruzzi278_logify
sonar.projectName=logify

sonar.sources=Backend,Frontend/src,Landing
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/coverage/**,**/*.test.js,**/*.test.ts,**/*.test.tsx,**/e2e/**,**/test-results/**,**/dev-dist/**

sonar.tests=Backend,Frontend/src
sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=Backend/orders-service/coverage/lcov.info,Backend/inventory-service/coverage/lcov.info,Backend/shipping-service/coverage/lcov.info,Backend/notification-service/coverage/lcov.info,Frontend/coverage/lcov.info
